# Generated by Django 3.2.18 on 2023-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField(max_length=200)),
                ('sympt', models.TextField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
