# Generated by Django 3.2.18 on 2023-04-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Med',
        ),
    ]
